feat(watt): styling of shell component
Energinet-DataHub/greenforce-frontend pull request #102
Opened 2021-11-10 07:43 UTC by dzhavat

## IMPORTANT

**This PR is based on #100. Merge this PR once #100 is on `main`.** 

---

## Description

### Watt Design System

- Style Shell component according to Figma (sidebar and toolbar)
- Make Shell component responsive on screen resolutions lower than `1279.98px`

## References

- https://github.com/Energinet-DataHub/MightyDucks/issues/215

## PLEASE NOTE

Before merging a frontend pull request, be sure that all checks have passed. Currently, jobs done by a Git-bot (like formatting and adding licenses) don't trigger a re-run of all the other checks. The "merge button" can therefore give you a false positive signal.

2021-11-10 14:34 UTC, frontend-specialisten requested changes
Besides the "closing button" is visible when you close, it looks good to me. Also the border of the toolbar should be clarified (for me et looks weird to have a border-right?)

2021-11-10 15:21 UTC, dzhavat commented
Should be fixed now. The border was changed to `border-bottom` only with a lighter value.

2021-11-11 08:49 UTC, frontend-specialisten approved these changes
LGTM

2021-11-11 08:59 UTC, stephaniegitha approved these changes

2021-11-11 09:00 UTC, merged