feat(dh): add function to validate metering point id
Energinet-DataHub/greenforce-frontend pull request #111
Opened 2021-11-12 15:52 UTC by dzhavat

## Description

### DataHub

* Create `dh/metering-point/domain` library
* Add function to validate metering point id

## References

- https://github.com/Energinet-DataHub/MightyDucks/issues/186

## PLEASE NOTE

Before merging a frontend pull request, be sure that all checks have passed. Currently, jobs done by a Git-bot (like formatting and adding licenses) don't trigger a re-run of all the other checks. The "merge button" can therefore give you a false positive signal.

2021-11-15 16:17 UTC, frontend-specialisten requested changes
Just some nitpicks :)

2021-11-15 16:17 UTC, frontend-specialisten commented on libs/dh/metering-point/domain/src/lib/is-metering-point-id.ts
> + * Validates that a metering point id is exactly 18 digits
Consider removing the amount of digits from the comment, otherwise it has to be maintained if the regex changes

2021-11-15 16:17 UTC, frontend-specialisten commented on libs/dh/metering-point/domain/src/lib/is-metering-point-id.ts
> +export function isMeteringPointId(maybeMeteringPointId: string): boolean {
Consider renaming the function to something like this, as we can't tell from this function if it's a `meteringPointId` however what it tells is if it's a valid metering point id
```suggestion
export function isValidMeteringPointId(maybeMeteringPointId: string): boolean {
```

2021-11-15 16:17 UTC, frontend-specialisten commented on libs/dh/metering-point/domain/src/lib/is-metering-point-id.spec.ts
> +    it('empty string', () => {
Consider writing your spec's like you're telling a story ex.
```suggestion
    it('should invalidate empty strings', () => {
```

2021-11-15 22:36 UTC, dzhavat commented
Feedback is addressed.

2021-11-16 06:44 UTC, frontend-specialisten commented
@dzhavat Question, should we include a custom form validator that uses this check as well or should I just create it in my branch?

2021-11-16 06:52 UTC, dzhavat commented
@frontend-specialisten This branch was not initially intended to be related to metering point search but figured out that the validation logic might be relevant. So I'd say lets create the custom validator in a separate branch. I'm also going to use the validation function in another branch for a route guard.

2021-11-16 06:53 UTC, frontend-specialisten approved these changes

2021-11-16 06:55 UTC, merged