feat(dh): add simple card in users tab under user management
Energinet-DataHub/greenforce-frontend pull request #1217
Opened 2022-12-08 14:07 UTC by dzhavat

## Description

### DataHub
- add simple card in users tab under user management
- generate user management data access api

![image](https://user-images.githubusercontent.com/1096332/206466510-58a7b208-f640-4bb6-bd52-bc107bfcf61d.png)

## References

- https://github.com/Energinet-DataHub/geh-post-office/issues/882

2022-12-08 14:20 UTC, mimse requested changes
Looks good, but are we not missing a dropdown shadow on the card?

2022-12-08 14:20 UTC, mimse commented on libs/dh/admin/feature-user-management/src/lib/user-management-tabs/dh-users-tab.component.html
> +      {{ t("singular", { numberOfUsers: numberOfUsers }) }}
Suggestion: use https://2ality.com/2019/12/intl-pluralrules.html to handle singular and plural

2022-12-09 07:25 UTC, dzhavat commented
> Looks good, but are we not missing a dropdown shadow on the card?

It's there but hidden by the tabs. It probably has an `overflow: hidden`.

2022-12-09 09:02 UTC, mimse approved these changes

2022-12-09 09:21 UTC, merged