Feature/dx git
Energinet-DataHub/greenforce-frontend pull request #1675
Opened 2023-04-27 06:29 UTC by mimse

Added two scripts. One for creating a branch from an github issue, the other creates a PR.

To create a branch from an issue you write yarn take

Choose a team

![image](https://user-images.githubusercontent.com/1250254/234777764-a652712a-33a8-4341-836b-9e3adc74ac66.png)

Now you can write the issue number or leave it blank to select from a list

![image](https://user-images.githubusercontent.com/1250254/234777989-ce19c499-93da-4b46-ae96-c37f768842ec.png)

![image](https://user-images.githubusercontent.com/1250254/234778041-6eedb640-32ea-479f-a376-90f76cae946c.png)

After selecting an issue press enter, and now the branch is created.

To create a PR, simply write yarn pr, and it open the PR web view on github

2023-04-28 10:20 UTC, ManBearTM requested changes
Great initiative!

I don't think this warrants a new top level folder named `dx`,  but should instead be placed under `tools` IMO. Also the name `dx` is too general I think, perhaps name it `github` since it contains helpers for automating github flows?

2023-04-28 10:20 UTC, ManBearTM commented on dx/create-branch-from-issue.js
> +    `gh issue develop ${issue} --issue-repo ${selectedRepo} --checkout`,
suggestion: this branch naming goes against our current naming strategy (branches prepended with `feature/`, `chore/`, `fix/` etc. I don't have strong opinions on the matter, but it should probably be cleared with the guild members if this is how it is going to be 🙂 Alternatively, you could prompt for which type of "branch" it is.

2023-04-28 10:20 UTC, ManBearTM commented on dx/create-pr.js
> +      exec(`gh pr create --base "${answers.branch}" --web`, (err, stdout, stderr) => {
question: i use gh pr create a lot and it is usually pretty good at figuring out the base branch by itself, so I don't love it if I have to choose it manually every time. maybe we can have an additional choice which is to "not set" the base branch (as in use whatever gh cli thinks is correct)?

2023-04-28 10:20 UTC, ManBearTM commented on package.json
> +    "pr": "node ./dx/create-pr.js"
suggestion: consider using [`ts-node`](https://github.com/TypeStrong/ts-node) so we can use TypeScript.

2023-05-04 13:22 UTC, mimse commented
@ManBearTM nice feedback, have implemented must of your ideas :-)

2023-05-08 11:56 UTC, ManBearTM approved these changes

2023-05-08 11:57 UTC, merged