feat(dh): load data in Balance responsible table
Energinet-DataHub/greenforce-frontend pull request #2080
Opened 2023-09-25 10:06 UTC by dzhavat

## Description

## References

- https://github.com/Energinet-DataHub/team-titans/issues/274

2023-09-25 11:04 UTC, mimse requested changes

2023-09-25 11:08 UTC, dzhavat commented on libs/dh/esett/feature-balance-responsible/src/lib/table/dh-table.component.html
> +      {{ message.supplier.value }}
Not according to the GraphQL query.

2023-09-25 11:08 UTC, dzhavat commented on libs/dh/esett/feature-balance-responsible/src/lib/table/dh-table.component.html
> +      {{ message.balanceResponsible.value }}
Not according to the GraphQL query.

2023-09-25 11:37 UTC, dzhavat commented on libs/dh/esett/feature-balance-responsible/src/lib/table/dh-table.component.html
> +    >
Good point, though keeping in mind that the `short` format will be used (which in this particular UI is fine).

Another problem I noticed is that the column's header is not translated anymore. So I had to use `resolveHeader` Input in the table for that.

2023-09-25 13:12 UTC, mimse submitted a review, later dismissed

2023-09-26 07:49 UTC, michaelmajgaard approved these changes

2023-09-26 07:51 UTC, merged