feat(watt): optimized stepper on smaller screens
Energinet-DataHub/greenforce-frontend pull request #2167
Opened 2023-10-20 06:11 UTC by Jaypeg85

## Description

- On smaller screens the title is only shown for the selected step
- Added story to storybook showcasing the stepper component in a modal
- Full screen modal on small screens now aligns the stepper buttons to the bottom of the page/dialog

## References

- #2165

2023-10-23 08:14 UTC, mimse requested changes

2023-10-23 08:14 UTC, mimse commented on libs/watt/src/lib/components/stepper/+storybook/stepper.modal.example.component.ts
> +  user = new FormBuilder().group({
Suggestion: inject formbuilder instead of creating a new instance everytime

2023-10-23 11:03 UTC, frontend-specialisten approved these changes

2023-10-24 06:38 UTC, mimse requested changes

2023-10-24 06:38 UTC, mimse commented on libs/watt/src/lib/components/stepper/+storybook/stepper.modal.example.component.ts
> +  address = new FormBuilder().group({ street: [''], city: [''] });
```suggestion
  address = this.formBuilder.group({ street: [''], city: [''] });
```

2023-10-24 06:38 UTC, mimse commented on libs/watt/src/lib/components/stepper/+storybook/stepper.modal.example.component.ts
> +  email = new FormBuilder().group({ email: [''] });
```suggestion
  email = this.formBuilder.group({ email: [''] });
```

2023-10-24 07:19 UTC, mimse approved these changes

2023-10-24 09:47 UTC, frontend-specialisten approved these changes

2023-10-24 09:47 UTC, merged