chore: code clean up
Energinet-DataHub/greenforce-frontend pull request #2781
Opened 2024-04-16 12:48 UTC by michaelmajgaard

2024-04-16 13:18 UTC, mimse requested changes

2024-04-16 13:18 UTC, mimse commented on apps/dh/api-dh/source/DataHub.WebApi/Program.cs
> +        .ConfigureOpenTelemetryTracerProvider((_, p) => p.AddHotChocolateInstrumentation())
```suggestion
        .ConfigureOpenTelemetryTracerProvider((_, builder) => builder.AddHotChocolateInstrumentation())
```

2024-04-16 13:40 UTC, defectiveAi approved these changes

2024-04-17 06:32 UTC, mimse approved these changes

2024-04-17 07:33 UTC, merged