chore: update tokens for nx cloud
Energinet-DataHub/greenforce-frontend pull request #38
Opened 2021-09-23 10:37 UTC by frontend-specialisten

Change tokens for nx cloud to be read-only in nx.json and read-write for our CI

2021-09-24 09:05 UTC, LayZeeDK requested changes

2021-09-24 09:05 UTC, LayZeeDK commented on .github/workflows/workspace.yml
> +  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
suggestion: can we organize environment variables alphabetically?
```suggestion
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_RUN_GROUP: ${{ github.run_id }}
```

2021-09-27 06:03 UTC, LayZeeDK approved these changes

2021-09-27 06:11 UTC, merged

2021-09-27 06:13 UTC, frontend-specialisten commented
@LayZeeDK Old token has now been revoked from nx cloud