Feature/caching
Energinet-DataHub/greenforce-frontend pull request #432
Opened 2022-03-25 07:34 UTC by Klemmensen

## Description

- Adds custom setting to production build in Webpack -> Images get a dynamic hash in their names to avoid caching issues

## References

https://github.com/Energinet-DataHub/energy-origin-issues/issues/405

2022-03-28 13:12 UTC, LayZeeDK submitted a review, later dismissed

2022-03-28 13:12 UTC, LayZeeDK commented on package.json
> +    "@angular-devkit/core": "12.2.16",
issue: revert this change

2022-03-28 13:57 UTC, LayZeeDK commented
With private browser tab open:
- [ ] Open feature environment
- [ ] Refresh, verify 304 responses
- [ ] Deploy changed JSON and image files
- [ ] Refresh, verify fresh 200 responses
- [ ] Deploy release without JSON and image file changes
- [ ] Refresh, verify 304 responses

2022-03-29 13:02 UTC, Chrisbh requested changes

2022-03-29 13:33 UTC, Chrisbh commented on infrastructure/eo/host/nginx.conf
> +		access_log    off;
Makes sense, thanks for the explanation. 

I would not usually accept having mixed tabs and spaces, I would go with one of them and stick to that. I am not sure what the standard is in this repository though.

2022-03-29 13:54 UTC, Klemmensen commented on infrastructure/eo/host/nginx.conf
> +		access_log    off;
Sure NP - Could you help me check again for the tabs, I converted the file to use tabs - Hopefully you see that too then?

2022-03-30 06:59 UTC, Chrisbh approved these changes

2022-03-30 07:09 UTC, merged