Create & edit organization and contacts
Energinet-DataHub/greenforce-frontend pull request #448
Opened 2022-04-05 12:57 UTC by defectiveAi

2022-04-28 12:22 UTC, dzhavat requested changes
praise: Good work so far! I bet RxJS is your favorite by now 😛

2022-04-28 14:12 UTC, defectiveAi commented on libs/dh/market-participant/feature-organization/src/lib/dh-market-participant-organization.component.html
> +          {{ element.actor?.gridAreas ?? "-" }}
gridArea is indeed missing at the moment, but will be added in the future. We still do want to show an empty column though, as it is currently the correct state. We have added a comment.

2022-04-29 07:12 UTC, defectiveAi commented on libs/dh/market-participant/data-access-api/src/lib/dh-market-participant-data-access-api.store.ts
> -  organizations: OrganizationWithActor[];
We refactored, it is saved once again.

2022-04-29 07:17 UTC, defectiveAi commented on libs/dh/market-participant/feature-edit-organization/src/lib/dh-market-participant-edit-organization/master-data/dh-market-participant-organization-master-data.component.html
> +        title="nameInput"
Nope, we removed the title.

2022-04-29 07:42 UTC, defectiveAi commented on libs/dh/market-participant/feature-edit-organization/src/lib/dh-market-participant-edit-organization/master-data/dh-market-participant-organization-master-data.component.ts
> +    );
Fixed, however, it appears the component does not refresh when the options are changed, unless the dropdown is opened and closed again.

2022-04-29 07:47 UTC, defectiveAi commented on libs/dh/market-participant/feature-edit-organization/src/lib/dh-market-participant-edit-organization/contact-data/dh-market-participant-organization-contact-data.component.html
> +            required
No, the red border is enough. We think it looks weird inside the table.

2022-04-29 07:47 UTC, defectiveAi commented on libs/dh/market-participant/feature-edit-organization/src/lib/dh-market-participant-edit-organization/contact-data/dh-market-participant-organization-contact-data.component.html
> +            required
No, the red border is enough. We think it looks weird inside the table.

2022-04-29 07:47 UTC, defectiveAi commented on libs/dh/market-participant/feature-edit-organization/src/lib/dh-market-participant-edit-organization/contact-data/dh-market-participant-organization-contact-data.component.html
> +            required
No, the red border is enough. We think it looks weird inside the table.

2022-04-29 08:02 UTC, defectiveAi commented on libs/dh/market-participant/data-access-api/src/lib/dh-market-participant-data-access-api.store.ts
> +    this.overviewList$ = this.setupRefreshListFlow();
Refactored, so the method no longer exist.

2022-05-03 05:50 UTC, dzhavat requested changes

2022-05-04 06:44 UTC, dzhavat approved these changes

2022-05-04 07:05 UTC, merged