Add Shell Component to Design System
Energinet-DataHub/greenforce-frontend pull request #47
Opened 2021-09-24 14:54 UTC by dzhavat

## Description

* Add Shell component to Watt Design System
* Create Storybook page where the component is showcased
* Refactor DataHub app to use a top-level lazy-loaded route
* Use Shell component in DataHub app

## References

- Energinet-DataHub/MightyDucks#132

2021-09-24 21:05 UTC, LayZeeDK requested changes

2021-09-24 21:05 UTC, LayZeeDK commented on libs/dh-app/core/feature-shell/src/lib/dh-app-core-feature-shell.module.ts
> +export class DhAppCoreFeatureShellModule {}
suggestion: a feature shell module contains root level routes, so we use `RouterModule.forRoot`
suggestion: make the feature shell idiomatic and simpler by deleting the separate routing module

```suggestion
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

import { ShellComponent } from './shell/shell.component';
import { ShellModule } from './shell/shell.module';

const routes: Routes = [
  {
    path: '',
    component: ShellComponent,
    children: [
      // Lazy feature routes
    ],
  },
];

@NgModule({
  exports: [RouterModule],
  imports: [RouterModule.forRoot(routes), ShellModule],
})
export class DhAppCoreFeatureShellModule {}
```

2021-09-24 21:05 UTC, LayZeeDK commented on libs/dh-app/core/feature-shell/src/lib/shell/shell.component.html
> +</watt-shell>
suggestion: add router outlet for app features

```suggestion
  <router-outlet></router-outlet>
</watt-shell>
```

2021-09-24 21:05 UTC, LayZeeDK commented on libs/dh-app/core/feature-shell/src/lib/shell/shell.module.ts
> +export class ShellModule {}
suggestion: support router outlet for app features

```suggestion
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { WattModule } from '@energinet/watt';

import { ShellComponent } from './shell.component';

@NgModule({
  declarations: [ShellComponent],
  imports: [RouterModule, WattModule],
})
export class ShellModule {}

```

2021-09-24 21:05 UTC, LayZeeDK commented on libs/dh-app/core/feature-shell/src/lib/shell/shell.component.html
> +  <ng-container sidenav>
suggestion: use a `watt-shell` prefix to be explicit about cohesive parts

```suggestion
  <ng-container watt-shell-sidenav>
```

2021-09-24 21:05 UTC, LayZeeDK commented on libs/dh-app/core/feature-shell/src/lib/shell/shell.component.html
> +  <ng-container toolbar>
suggestion: use a `watt-shell` prefix to be explicit about cohesive parts

```suggestion
  <ng-container watt-shell-toolbar>
```

2021-09-28 08:17 UTC, frontend-specialisten approved these changes
I think this looks good as an MVP. When we have the colors, breakpoints, sizes and theming we can apply some default styles and add open / close for the sidebar. 
Also I think we should create a task for sidebar navigation items, which are styled by our design

2021-09-28 10:38 UTC, dzhavat commented
I've omitted anything related to spacing, theming, open/close functionality because these are not defined yet. There are probably some commonly used ways to toggle a sidebar, which we can also add, but I haven't seen how our Design System handles it. That's why it's yet to be implemented.

2021-09-28 13:51 UTC, dzhavat commented
@LayZeeDK Do you see the need for you reviewing this PR as well?

2021-09-29 11:03 UTC, LayZeeDK approved these changes

2021-09-29 11:17 UTC, merged