feat(ui-watt): add single selection of datepicker
Energinet-DataHub/greenforce-frontend pull request #511
Opened 2022-05-05 07:27 UTC by frontend-specialisten

## Description

## References

- #0000

2022-05-11 13:11 UTC, dzhavat requested changes

2022-05-11 13:11 UTC, dzhavat commented on libs/ui-watt/src/lib/components/input/datepicker/+storybook/watt-datepicker-reactive-forms.stories.ts
> +  <watt-datepicker [formControl]="exampleFormControlRange" range></watt-datepicker>
issue: in VS Code I get the following error if I simply use the `range` attribute.

![image](https://user-images.githubusercontent.com/1096332/167855895-908ca304-c57c-4e3b-88d8-48489d2c6197.png)

Let's use the "expanded" version, i.e. `[range]="true"` when displaying a date range picker.

2022-05-16 06:53 UTC, frontend-specialisten reviewed
@cla-bot check

2022-05-16 06:53 UTC, dzhavat approved these changes

2022-05-16 06:56 UTC, Renetnielsen commented
@cla-bot check

2022-05-16 06:56 UTC, dzhavat commented
@cla-bot check

2022-05-16 06:57 UTC, frontend-specialisten commented
@cla-bot check

2022-05-16 06:58 UTC, frontend-specialisten commented
@cla-bot check

2022-05-16 07:02 UTC, merged