market roles tests
Energinet-DataHub/greenforce-frontend pull request #558
Opened 2022-05-24 07:36 UTC by xnetsrak

## Description

init marketrole component tests added

## References

- #0000

2022-05-24 09:05 UTC, frontend-specialisten requested changes
Looks good, only a single `suggestion` and some `nitpicks` you can consider :)

2022-05-24 09:05 UTC, frontend-specialisten commented on libs/dh/market-participant/feature-edit-actor/src/lib/market-participant-edit-actor/market-roles/dh-market-participant-actor-market-roles.component.spec.ts
> +    const allOptions = screen.getAllByRole('option');
Nitpick: common queries can also be extracted to provide reduce duplications but still keeping the readability. This example could be `getAllOptions = () => screen.getAllByRole('option')` which returns the query.

2022-05-24 14:23 UTC, frontend-specialisten approved these changes

2022-05-24 15:07 UTC, dzhavat commented on libs/dh/market-participant/feature-edit-actor/src/lib/market-participant-edit-actor/market-roles/dh-market-participant-actor-market-roles.component.spec.ts
> +  });
suggestion: it'd be nice to have at least one test that covers the output functionality. It's an important functionality for this component.

2022-05-25 07:06 UTC, xnetsrak commented on libs/dh/market-participant/feature-edit-actor/src/lib/market-participant-edit-actor/market-roles/dh-market-participant-actor-market-roles.component.spec.ts
> +describe('MarketRolesChk', () => {
tests dit not run on name change

2022-05-25 13:36 UTC, closed without merging