actor contacts API in BFF
Energinet-DataHub/greenforce-frontend pull request #572
Opened 2022-06-01 06:58 UTC by michaelmajgaard

2022-06-03 09:11 UTC, frontend-specialisten reviewed
Looks good, only a few comments you can consider :)

2022-06-03 09:11 UTC, frontend-specialisten commented on libs/dh/market-participant/feature-edit-actor/src/lib/market-participant-edit-actor/contact-data/dh-market-participant-actor-contact-data.component.ts
>    ngOnChanges() {
Suggestion: Add argument for `ngOnChanges` like example below, and adjust the `if statement` only to care about if `contacts` has changed.   

[ngOnChanges(changes: SimpleChanges): void](https://angular.io/api/core/OnChanges#ngOnChanges)

2022-06-03 09:11 UTC, frontend-specialisten commented on libs/dh/market-participant/feature-edit-actor/src/lib/market-participant-edit-actor/dh-market-participant-edit-actor.component.ts
> +import { DhMarketParticipantActorContactDataComponentScam } from './contact-data/dh-market-participant-actor-contact-data.component';
Nitpick: order the imports 
1. Third party deps 
2. Internal deps from other libraries 
3. Relative deps

2022-06-03 09:11 UTC, frontend-specialisten commented on libs/dh/market-participant/feature-edit-organization/src/lib/market-participant-edit-organization/dh-market-participant-edit-organization.component.html
> +    <ng-container *rxLet="organization$ as organization">
Nitpick: Consider using `template-binding` and remember to handle the error states as well. 
https://github.com/rx-angular/rx-angular/blob/main/libs/template/docs/api/let-directive.md#using-the-template-binding

2022-06-05 08:00 UTC, michaelmajgaard commented on libs/dh/market-participant/feature-edit-actor/src/lib/market-participant-edit-actor/contact-data/dh-market-participant-actor-contact-data.component.spec.ts
> +    const category = screen.getAllByRole('option')[2];
This was the only way, I could make it work. I tried with test ID's, but the test then fails with the following; `A better query is available, try this: getByRole('textbox')`

2022-06-05 08:02 UTC, michaelmajgaard commented on libs/dh/market-participant/data-access-api/src/lib/dh-market-participant-edit-actor-data-access-api.store.ts
> +        this.httpClient.v1MarketParticipantOrganizationOrgIdActorActorIdContactContactIdDelete(
We want to break the chain in case of an error

2022-06-05 08:03 UTC, michaelmajgaard commented on libs/dh/market-participant/data-access-api/src/lib/dh-market-participant-edit-actor-data-access-api.store.ts
> +        this.httpClient.v1MarketParticipantOrganizationOrgIdActorActorIdContactPost(
We want to break the chain in case of an error

2022-06-07 09:36 UTC, frontend-specialisten commented on libs/dh/market-participant/feature-edit-actor/src/lib/market-participant-edit-actor/contact-data/dh-market-participant-actor-contact-data.component.spec.ts
> +    const category = screen.getAllByRole('option')[2];
What you can do is applying `aria-labels` instead. Ex. for the combobox you can do something like this (note that the label properly should be changed according to the dropdown is for a new or editing an existing contact `[attr.aria-label]="isNew ? 'category for new contact' : 'something else'"`):
_HTML_
` <watt-dropdown
            required
            [options]="contactCategories"
            [(ngModel)]="element.changed.category"
            (ngModelChange)="onDropdownChanged(element)"
            aria-label="category for new contact"
          >`
_Spec_
`
const cellOfCategoryForNewContact = screen.getByRole('cell', { name: /category for new contact/i });
const combobox = within(cellOfCategoryForNewContact).getByRole('combobox');
userEvent.click(combobox);
`

2022-06-07 09:39 UTC, frontend-specialisten commented on libs/dh/market-participant/feature-edit-organization/src/lib/market-participant-edit-organization/dh-market-participant-edit-organization.component.html
> +    <ng-container *rxLet="organization$ as organization">
My comment was regarding using `rxError`, `rxSuspense` and `rxComplete` to make it easier to handle the different states of the template.

2022-06-07 13:49 UTC, frontend-specialisten requested changes

2022-06-07 13:49 UTC, frontend-specialisten commented on libs/dh/market-participant/feature-edit-actor/src/lib/market-participant-edit-actor/contact-data/dh-market-participant-actor-contact-data.component.html
> +                ? 'delete for existing contact'
This label is also used by screen-readers, so maybe just remove `for` here? 
```suggestion
                ? 'delete existing contact'
```

2022-06-07 14:24 UTC, michaelmajgaard commented on libs/dh/market-participant/feature-edit-actor/src/lib/market-participant-edit-actor/contact-data/dh-market-participant-actor-contact-data.component.html
> +              element.isExisting
It is shown on both existing and new rows

2022-06-09 06:09 UTC, frontend-specialisten approved these changes

2022-06-09 08:15 UTC, merged