Fix "No provider for InjectionToken mat-datepicker-scroll-strategy"
Energinet-DataHub/greenforce-frontend pull request #681
Opened 2022-06-30 06:49 UTC by frontend-specialisten

## Description

- Fix "No provider for InjectionToken mat-datepicker-scroll-strategy"
- Corrected naming of the `WattTimePickerModule`

## References

- #0000

2022-06-30 08:27 UTC, ManBearTM commented
What happened with this commit?
https://github.com/Energinet-DataHub/greenforce-frontend/pull/681/commits/8e6887a217a76238c2a48204b3f36c44a713d4ba

2022-06-30 11:39 UTC, dzhavat requested changes

2022-06-30 11:39 UTC, dzhavat commented on libs/dh/market-participant/feature-edit-actor/src/lib/market-participant-edit-actor/dh-market-participant-edit-actor.component.html
> +</watt-form-field>
nitpick: clean up :)

2022-06-30 11:39 UTC, dzhavat commented on libs/dh/market-participant/feature-edit-actor/src/lib/market-participant-edit-actor/dh-market-participant-edit-actor.component.ts
> +    ReactiveFormsModule,
nitpick: clean up :)

2022-06-30 11:39 UTC, dzhavat commented on libs/dh/message-archive/feature-log-search/src/lib/dh-message-archive-log-search.component.html
> +        <watt-datepicker></watt-datepicker>
nitpick: clean up :)

2022-06-30 11:39 UTC, dzhavat commented on libs/ui-watt/src/lib/components/input/datepicker/watt-datepicker.component.ts
> +    MAT_DATEPICKER_SCROLL_STRATEGY_FACTORY_PROVIDER,
question: seems like this provider is already provided in the `MatDatepickerModule` (https://github.com/angular/components/blob/main/src/material/datepicker/datepicker-module.ts#L85). I wonder why is it needed again. Any idea?

2022-06-30 11:40 UTC, dzhavat commented on libs/dh/shared/data-access-msw/src/lib/mocks/market-participant/market-participant.ts
> +      );
issue: SonarCloud complains about unreachable code. Maybe this should be commented out?

2022-06-30 11:50 UTC, frontend-specialisten commented
> What happened with this commit? [8e6887a](https://github.com/Energinet-DataHub/greenforce-frontend/commit/8e6887a217a76238c2a48204b3f36c44a713d4ba)

Messed up commit has now been reverted.

2022-06-30 12:00 UTC, dzhavat submitted a review, later dismissed

2022-07-01 06:27 UTC, dzhavat approved these changes

2022-07-01 06:28 UTC, merged